
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 1.0
title = "Alacritty"
decorations = "none"

[window.padding]
x = 26
y = 26
